apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ required "Cluster name should be provided with .Values.name" .Values.name }}
spec:
  kafka:
    version: {{ .Values.kafka.version }}
    replicas: {{ .Values.replicas }}
    listeners:
      {{- range .Values.kafka.listeners }}
      - name: {{ .name }}
        port: {{ .port }}
        type: {{ .type }}
        tls: {{ .tls }}
      {{- end }}
    config:
      {{- toYaml .Values.kafka.config | nindent 6 }}
    storage:
      type: persistent-claim
      deleteClaim: {{ .Values.kafka.storage.deleteClaim | default false}}
      size: {{ .Values.kafka.storage.size }}
      class: {{ .Values.kafka.storage.class | default "default" }}

  zookeeper:
    replicas: {{ .Values.zookeeper.replicas }}
    storage:
      type: persistent-claim
      deleteClaim: {{ .Values.kafka.storage.deleteClaim | default false }}
      size: {{ .Values.kafka.storage.size }}
      class: {{ .Values.kafka.storage.class | default "default" }}

  entityOperator:
    topicOperator: {}
    userOperator: {}


replicas: 3
storageSize: "10Gi"

name: dev-kafka-cluster

kafka:
  version: "3.5.0"
  listeners:
  - name: plain
    port: 9092
    type: internal
    tls: false
  - name: tls
    port: 9093
    type: internal
    tls: true
  config:
    offsets.topic.replication.factor: 3
    transaction.state.log.replication.factor: 3
    transaction.state.log.min.isr: 2
    default.replication.factor: 3
    min.insync.replicas: 2
    inter.broker.protocol.version: "3.5"
  storage:
    size: "10Gi"

zookeeper:
  replicas: 3
  storage:
    size: "10Gi"

entityOperator:
  topicOperator: {}
  userOperator: {}
